###Create user

POST http://localhost:3001/api
Content-Type: application/json

{
    "name": "NewImproUser"
}

### Get all users

GET http://localhost:3001/api

### Add new item - Change user id accorning to the ones you get in response

PATCH http://localhost:3001/api/60ea9c71735bdc07861f3385
Content-Type: application/json

{
    "newItem": "MyItem" 
}

### Delete user - Change user id accorning to the ones you get in response

DELETE http://localhost:3001/api/60ea9c71735bdc07861f3385

### Update user name - Change user id accorning to the ones you get in response

PATCH  http://localhost:3001/api/update/60ea9c71735bdc07861f3385
Content-Type: application/json

{
    "name": "ImproNewName"
}