POST http://localhost:3001/
Content-Type: application/json

{
    "name": "TestUser"
}

### Get all users

GET http://localhost:3001/

### Add new item

PATCH http://localhost:3001/60d5e3c51036f83d9737ac0d
Content-Type: application/json

{
    "newItem": "A" 
}

### Delete user

DELETE http://localhost:3001/60d35f5663c1c50a5e678791

### Update user name

PATCH  http://localhost:3001/update/60d229eb28c1da0880630526
Content-Type: application/json

{
    "name": "SomeOne"
}