POST http://localhost:3001/
Content-Type: application/json

{
    "name": "TestUser"
}

### Get all users

GET http://localhost:3001/

### Add new item

PATCH http://localhost:3001/60d5e8fac1c99647a2bb0bee
Content-Type: application/json

{
    "newItem": "Piano" 
}

### Delete user

DELETE http://localhost:3001/60d5e3c51036f83d9737ac0d

### Update user name

PATCH  http://localhost:3001/update/60d229eb28c1da0880630526
Content-Type: application/json

{
    "name": "SomeOne"
}